services:
  beets-flask:
    container_name: beets-flask
    hostname: beets-container
    build:
      context: .
      dockerfile: Dockerfile
      target: prod
      args:
        USER_ID: 568
        GROUP_ID: 568
    image: beets-flask
    restart: unless-stopped
    ports:
      - 5001:5001
    environment:
      - PUID=568
      - PGID=568
      - TZ=Europe/London    
      - LOG_LEVEL_BEETSFLASK=INFO
      - LOG_LEVEL_OTHERS=WARNING
    volumes:
      - /mnt/audio/music:/music
      - /mnt/docker/beets-flask:/home/beetle
      - /mnt/downloads:/downloads
networks: {}
